EdTech/Controllers/CoursesController.cs
using EdTech.Assests;
using EdTech.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Internal;
using Microsoft.SqlServer.Server;

namespace EdTech.Controllers
{
    public class CoursesController : Controller
    {
        private readonly AppDbContext _context;
        public CoursesController(AppDbContext context)
        {
            _context = context;
        }


        //Courses/
        public IActionResult Index()
        {
            var data = _context.Courses.ToList();
            return View(data);
        }
        //Courses/addCourse
        public IActionResult addCourse()
        {
    
            return View();

        }
        [HttpPost]
        public IActionResult addCourse(Courses formData)
        {

            Courses course = new Courses();
            course.isDeleted = false;
            course.CreatedAt = DateTime.Now;
            course.ModifiedAt = DateTime.Now;
            course.CourseOrder = formData.CourseId;
            course.CourseImage = formData.CourseImage;
            course.CourseDesc = formData.CourseDesc;
            course.CourseName = formData.CourseName;
            course.AuthorId = 1;
            course.SubjectName = formData.SubjectName;
            
            //if (!ModelState.IsValid)
            //{
            //    return View(formData);
            //}
           
            _context.Courses.Add(course);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
        public IActionResult editCourse(int id)
        {
            var courseDetails = _context.Courses.FirstOrDefault(x => x.CourseId == id);
            return View(courseDetails);
        }
        [HttpPost]
        public IActionResult editCourse(Courses editCourseData)
        {
            Courses course = new Courses();
            course.isDeleted = false;
            course.CreatedAt = editCourseData.CreatedAt;
            course.ModifiedAt = DateTime.Now;
            course.CourseOrder = editCourseData.CourseId;
            course.CourseImage = editCourseData.CourseImage;
            course.CourseDesc = editCourseData.CourseDesc;
            course.CourseName = editCourseData.CourseName;
            course.AuthorId = 1;
            course.SubjectName = editCourseData.SubjectName;

            _context.Courses.Update(course);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
        public IActionResult deleteCourse(int id)
        {
            var courseDetails = _context.Courses.FirstOrDefault(x => x.CourseId == id);
            return View(courseDetails);
        }
        [HttpPost,ActionName("deleteCourse")]
        public IActionResult deleteCourseById(int id)
        {
            var deleteData = _context.Courses.FirstOrDefault(x => x.CourseId == id);
            _context.Courses.Remove(deleteData);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
    }
}

EdTech/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EdTech</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EdTech.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/flex-slider.css"/>
    <link rel="stylesheet" href="~/css/lightbox.css"/>
    <link rel="stylesheet" href="~/css/templatemo-eduwell-style.css" />
    
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EdTech</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Courses" asp-action="Index">Courses</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Subjects" asp-action="Index">Subjects</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    <div>
                        <button class="btn btn-primary">SignUp</button>
                    </div>
                </div>
            </div>
        </nav>
    </header>
@*     <header class="header-area header-sticky">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <nav class="main-nav">
                        <!-- ***** Logo Start ***** -->
                        <a href="index.html" class="logo">
                            <img src="assets/images/templatemo-eduwell.png" alt="EduWell Template">
                        </a>
                        <!-- ***** Logo End ***** -->
                        <!-- ***** Menu Start ***** -->
                        <ul class="nav">
                            <li class="scroll-to-section"><a href="#top" class="active">Home</a></li>
                            <li class="scroll-to-section"><a href="#services">Services</a></li>
                            <li class="scroll-to-section"><a href="#courses">Courses</a></li>
                            <li class="has-sub">
                                <a href="javascript:void(0)">Pages</a>
                                <ul class="sub-menu">
                                    <li><a href="about-us.html">About Us</a></li>
                                    <li><a href="our-services.html">Our Services</a></li>
                                    <li><a href="contact-us.html">Contact Us</a></li>
                                </ul>
                            </li>
                            <li class="scroll-to-section"><a href="#testimonials">Testimonials</a></li>
                            <li class="scroll-to-section"><a href="#contact-section">Contact Us</a></li>
                        </ul>
                        <a class='menu-trigger'>
                            <span>Menu</span>
                        </a>
                        <!-- ***** Menu End ***** -->
                    </nav>
                </div>
            </div>
        </div>
    </header> *@
    <div >
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - EdTech - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/slick-slider.js"></script>
    <script src="~/js/tabs.js"></script>
    <script src="~/js/custom.js"></script>
    <script src="~/js/video.js"></script>
    <script src="~/js/"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>